// AI Tutor: a conversation with TradeLab Tutor.
// In preview mode the replies are prewritten explanations matched by topic,
// and the interface says so on every reply. The chat UI only talks to
// tutorService, so a llama.cpp-backed API can replace the mock later
// without changing this page.

import { html, raw, render, on, createDisposer, toElement, $ } from '../utils/dom.js';
import { getState, watch } from '../state.js';
import { markdownToHTML } from '../utils/markdown.js';
import { clockTime } from '../utils/format.js';
import { icon, logoMark } from '../components/icons.js';
import { confirmDialog } from '../components/modals.js';
import { sendMessage, clearConversation, isPreviewMode, MAX_MESSAGE_LENGTH } from '../services/tutorService.js';
import { catalog } from '../services/progressService.js';
import { SUGGESTED_QUESTIONS } from '../data/mockTutorResponses.js';

function avatar() {
  return html`<span class="msg__avatar" aria-hidden="true">${logoMark({ className: 'msg__mark' })}</span>`;
}

function sourceLabel(meta) {
  if (meta?.source === 'mock') return html`<span class="pill" title="Matched to a prewritten explanation, not generated by a language model">Prewritten answer</span>`;
  if (meta?.source === 'llm') return html`<span class="pill">Generated${meta.model ? ` by ${meta.model}` : ''}</span>`;
  return '';
}

function message(msg) {
  if (msg.role === 'user') {
    return html`<div class="msg msg--user">
      <div class="msg__bubble"><p class="msg__text">${msg.content}</p></div>
      <p class="msg__meta"><span class="sr-only">You said, </span>${clockTime(msg.createdAt)}</p>
    </div>`;
  }
  if (msg.meta?.source === 'error') {
    return html`<div class="msg msg--assistant msg--error">${avatar()}
      <div class="msg__body">
        <p class="msg__meta"><span class="msg__name">TradeLab Tutor</span><span>${clockTime(msg.createdAt)}</span></p>
        <p class="callout callout--warn">${icon('alert', { className: 'callout__icon' })}<span>${msg.content}</span></p>
      </div>
    </div>`;
  }
  return html`<div class="msg msg--assistant">${avatar()}
    <div class="msg__body">
      <p class="msg__meta"><span class="msg__name">TradeLab Tutor</span>${sourceLabel(msg.meta)}<span>${clockTime(msg.createdAt)}</span></p>
      <div class="prose prose--sm msg__content">${raw(markdownToHTML(msg.content))}</div>
    </div>
  </div>`;
}

function intro() {
  return html`<div class="msg msg--assistant msg--intro">${avatar()}
    <div class="msg__body">
      <p class="msg__meta"><span class="msg__name">TradeLab Tutor</span>${isPreviewMode() ? html`<span class="pill">Preview mode</span>` : ''}</p>
      <div class="prose prose--sm">
        <p>Hi! I explain trading concepts in plain language and can walk through your own simulated trades.</p>
        ${isPreviewMode()
          ? html`<p>Right now I'm a preview: I answer from a set of prewritten explanations on beginner topics rather than a language model, so I can't handle every question. A locally hosted model is planned.</p>`
          : ''}
        <p>Pick a question below or type your own.</p>
      </div>
    </div>
  </div>`;
}

function pending() {
  return html`<div class="msg msg--assistant msg--pending">${avatar()}
    <div class="msg__body">
      <p class="msg__meta"><span class="msg__name">TradeLab Tutor</span></p>
      <p class="msg__typing"><span class="dots" aria-hidden="true"><i></i><i></i><i></i></span>${isPreviewMode() ? 'Finding a prewritten answer…' : 'Thinking…'}</p>
    </div>
  </div>`;
}

function suggestionChips(disabled) {
  return SUGGESTED_QUESTIONS.map(
    (question) => html`<button type="button" class="chip" data-ask="${question}" ${disabled ? 'disabled' : ''}>${question}</button>`,
  );
}

export default {
  id: 'tutor',
  mount(root, { query }) {
    const disposer = createDisposer();
    render(
      root,
      html`<div class="page tutor">
        <div class="tutor-layout">
          <section class="panel chat" aria-labelledby="chat-title">
            <div class="panel__head chat__head">
              <div class="cluster">
                <h2 class="panel__title" id="chat-title">TradeLab Tutor</h2>
                ${isPreviewMode() ? html`<span class="pill" title="Replies are prewritten explanations, not generated by a language model">Preview: prewritten answers</span>` : ''}
              </div>
              <button type="button" class="btn btn--ghost btn--sm" data-action="clear">${icon('trash')}Clear conversation</button>
            </div>
            <div class="chat__log" id="chat-log" role="log" aria-label="Conversation with TradeLab Tutor" tabindex="0"></div>
            <form class="chat__composer" id="chat-form" novalidate>
              <div class="chat__suggestions" id="chat-suggestions" role="group" aria-label="Suggested questions"></div>
              <div class="chat__inputrow">
                <label class="sr-only" for="chat-input">Message TradeLab Tutor</label>
                <textarea class="textarea chat__input" id="chat-input" rows="1" maxlength="${MAX_MESSAGE_LENGTH}" placeholder="Ask about a concept or your trades" aria-describedby="chat-hint"></textarea>
                <button type="submit" class="btn btn--primary chat__send" id="chat-send" aria-label="Send message">${icon('send')}<span class="chat__send-label">Send</span></button>
              </div>
              <p class="chat__hint" id="chat-hint"><span>Enter to send, Shift+Enter for a new line.</span><span>Educational explanations, not financial advice.</span><span class="chat__count" id="chat-count"></span></p>
            </form>
          </section>
          <aside class="tutor-side stack">
            <section class="panel" aria-labelledby="about-tutor">
              <div class="panel__head panel__head--plain"><h2 class="panel__title" id="about-tutor">About this tutor</h2></div>
              <div class="panel__body stack-sm small muted">
                ${isPreviewMode()
                  ? html`<p>This is a <strong>preview</strong>. Replies come from prewritten explanations matched to your question by topic. Nothing is sent to an AI service.</p>
                      <p>A version powered by a locally hosted language model (llama.cpp, through a Flask backend) is planned and will use this same chat.</p>`
                  : html`<p>Replies are generated by TradeLab's tutor model running on your own server.</p>`}
                <p>The tutor explains concepts; it never tells you what to buy or sell, and every account it can see is simulated.</p>
              </div>
            </section>
            <section class="panel" aria-labelledby="topics-title">
              <div class="panel__head panel__head--plain"><h2 class="panel__title" id="topics-title">Topics it covers</h2></div>
              <div class="panel__body">
                <ul class="topic-list small">
                  <li><a class="link" href="#/learn/candlestick-anatomy">Candlestick charts</a></li>
                  <li><a class="link" href="#/learn/market-vs-limit-orders">Market and limit orders</a></li>
                  <li><a class="link" href="#/learn/position-sizing">Risk-to-reward and position sizing</a></li>
                  <li><a class="link" href="#/learn/diversification-basics">Diversification and index funds</a></li>
                  <li><a class="link" href="#/learn/moving-averages">Moving averages and RSI</a></li>
                  <li><a class="link" href="#/learn/trading-psychology">Trading psychology</a></li>
                  <li>Your last simulated trade and your portfolio</li>
                </ul>
              </div>
            </section>
          </aside>
        </div>
      </div>`,
    );

    const log = $('#chat-log', root);
    const input = $('#chat-input', root);
    const send = $('#chat-send', root);
    const count = $('#chat-count', root);
    let renderedIds = [];

    // Sent with every message so a backend model knows where the learner is.
    // Opening the tutor from a lesson (#/tutor?ask=..&lesson=<id>) adds the lesson.
    const pageContext = { route: 'tutor', ...(query.lesson && catalog.getLesson(query.lesson) ? { lessonId: query.lesson } : {}) };

    const nearBottom = () => log.scrollHeight - log.scrollTop - log.clientHeight < 80;

    // Messages are appended rather than re-rendered, so screen readers only
    // announce what is new in the conversation log.
    const paintLog = ({ forceScroll = false } = {}) => {
      const { messages } = getState().tutor;
      const stick = forceScroll || nearBottom();
      const sameStart = renderedIds.length <= messages.length && renderedIds.every((id, i) => messages[i]?.id === id);
      if (!sameStart || renderedIds.length === 0) {
        render(log, html`${intro()}<div class="chat__messages">${messages.map(message)}</div><div class="chat__pending" aria-hidden="true"></div>`);
      } else {
        const list = log.querySelector('.chat__messages');
        for (const msg of messages.slice(renderedIds.length)) list.appendChild(toElement(message(msg)));
      }
      renderedIds = messages.map((msg) => msg.id);
      render(log.querySelector('.chat__pending'), getState().runtime.tutorPending ? pending() : '');
      if (stick) log.scrollTop = log.scrollHeight;
    };

    const paintComposer = () => {
      const isPending = getState().runtime.tutorPending;
      const empty = getState().tutor.messages.length === 0;
      render($('#chat-suggestions', root), html`${suggestionChips(isPending)}`);
      $('#chat-suggestions', root).classList.toggle('chat__suggestions--compact', !empty);
      send.disabled = isPending || input.value.trim() === '';
      const remaining = MAX_MESSAGE_LENGTH - input.value.length;
      count.textContent = remaining < 200 ? `${remaining} characters left` : '';
    };

    const autosize = () => {
      input.style.height = 'auto';
      input.style.height = `${Math.min(input.scrollHeight, 180)}px`;
    };

    const ask = async (text) => {
      const value = String(text ?? '').trim();
      if (!value || getState().runtime.tutorPending) return;
      input.value = '';
      autosize();
      paintComposer();
      await sendMessage(value, pageContext);
    };

    paintLog({ forceScroll: true });
    paintComposer();

    disposer.add(
      on(root, 'submit', '#chat-form', (event) => {
        event.preventDefault();
        ask(input.value);
      }),
    );
    disposer.add(
      on(root, 'keydown', '#chat-input', (event) => {
        if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
          event.preventDefault();
          ask(input.value);
        }
      }),
    );
    disposer.add(
      on(root, 'input', '#chat-input', () => {
        autosize();
        paintComposer();
      }),
    );
    disposer.add(on(root, 'click', '[data-ask]', (_event, button) => ask(button.dataset.ask)));
    disposer.add(
      on(root, 'click', '[data-action="clear"]', async () => {
        if (!getState().tutor.messages.length) {
          input.focus();
          return;
        }
        const confirmed = await confirmDialog({
          title: 'Clear the conversation?',
          message: 'All messages in this conversation will be removed from this browser.',
          confirmLabel: 'Clear conversation',
          danger: true,
        });
        if (confirmed) {
          clearConversation();
          input.focus();
        }
      }),
    );

    disposer.add(
      watch((state) => state.tutor.messages, () => {
        paintLog({ forceScroll: true });
        paintComposer();
      }),
    );
    disposer.add(
      watch((state) => state.runtime.tutorPending, () => {
        paintLog({ forceScroll: true });
        paintComposer();
        if (!getState().runtime.tutorPending && root.contains(document.activeElement) === false) input.focus({ preventScroll: true });
      }),
    );

    // Deep link from elsewhere in the app: #/tutor?ask=<question>
    if (query.ask) {
      const question = String(query.ask).slice(0, MAX_MESSAGE_LENGTH);
      try {
        window.history.replaceState(null, '', '#/tutor');
      } catch {
        // Ignored in viewers that block history updates.
      }
      queueMicrotask(() => ask(question));
    } else {
      input.focus({ preventScroll: true });
    }

    return () => disposer.dispose();
  },
};
